[package]
name              = "oozems-wz-editor"
version.workspace = true
edition           = "2024"
license.workspace = true

[dependencies]
anyhow = "1.0.104"
eframe = { version = "0.36.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
oozems-wz = { version = "0.1.0", path = "../oozems-wz" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tempfile = "3.27.0"
thiserror = "2.0.20"
toml = "1.1.4"

[lints]
workspace = true
