use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::Path;

use anyhow::Context;
use anyhow::Result;
use anyhow::bail;
use tempfile::NamedTempFile;

use super::model::CatalogGlobalDrop;
use super::model::ItemDrop;
use super::model::LootCatalog;
use super::model::MesoDrop;
use super::model::MobDrop;
use crate::Region;

pub(crate) fn render(
    catalog: &LootCatalog,
    region: Region,
    versions: &std::collections::BTreeMap<String, i16>,
) -> String {
    let mut output = String::new();
    writeln!(output, "# Generated by oozems-wz generate-loot.").unwrap();
    writeln!(
        output,
        "# Provenance: metadata and validation facts come from the local WZ archives."
    )
    .unwrap();
    writeln!(
        output,
        "# Rates, formulas, quantities, globals, and explicit drops are Oozems-authored policy."
    )
    .unwrap();
    writeln!(
        output,
        "# Reactor tables are not generated because WZ has no reactor-to-item relationships."
    )
    .unwrap();
    writeln!(output, "# Policy: {}", one_line(&catalog.policy_name)).unwrap();
    write!(output, "# WZ source: region={}", region_name(region)).unwrap();
    for (archive, version) in versions {
        write!(output, " {}={version}", one_line(archive)).unwrap();
    }
    writeln!(output, "\n").unwrap();

    for drop in &catalog.global_drops {
        writeln!(output, "[[global_drops]]").unwrap();
        match drop {
            CatalogGlobalDrop::Item(item) => {
                writeln!(output, "item_id = {}", item.item_id).unwrap();
                writeln!(output, "chance_per_million = {}", item.chance_per_million).unwrap();
                if let (Some(minimum), Some(maximum)) =
                    (item.minimum_quantity, item.maximum_quantity)
                {
                    writeln!(output, "minimum_quantity = {minimum}").unwrap();
                    writeln!(output, "maximum_quantity = {maximum}").unwrap();
                }
                if let Some(quest_id) = item.quest_id {
                    writeln!(output, "quest_id = {quest_id}").unwrap();
                }
            }
            CatalogGlobalDrop::Mesos(mesos) => write_meso_values(
                &mut output,
                mesos.chance_per_million,
                mesos.minimum_mesos,
                mesos.maximum_mesos,
            ),
        }
        writeln!(output).unwrap();
    }

    for mob in &catalog.mobs {
        if let Some(name) = &mob.name {
            writeln!(output, "# {}", one_line(name)).unwrap();
        }
        writeln!(output, "[[mobs]]").unwrap();
        writeln!(output, "mob_id = {}", mob.mob_id).unwrap();
        for drop in &mob.drops {
            writeln!(output).unwrap();
            writeln!(output, "[[mobs.drops]]").unwrap();
            match drop {
                MobDrop::Item(item) => write_item(&mut output, *item),
                MobDrop::Mesos(mesos) => write_mesos(&mut output, *mesos),
            }
        }
        writeln!(output).unwrap();
    }
    while output.ends_with("\n\n") {
        output.pop();
    }
    output
}

pub(crate) fn write_atomic(
    output: &Path,
    contents: &str,
    force: bool,
) -> Result<()> {
    if output.exists() && !force {
        bail!(
            "output already exists: {} (use --force to replace it)",
            output.display()
        );
    }
    let parent = output
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    if !parent.is_dir() {
        bail!("output directory does not exist: {}", parent.display());
    }
    let mut temporary = NamedTempFile::new_in(parent)
        .with_context(|| format!("failed to create a temporary file in {}", parent.display()))?;
    temporary
        .write_all(contents.as_bytes())
        .with_context(|| format!("failed to write generated loot {}", output.display()))?;
    temporary.as_file().sync_all()?;
    if force {
        temporary.persist(output).map_err(|error| error.error)?;
    } else {
        temporary
            .persist_noclobber(output)
            .map_err(|error| error.error)?;
    }
    if let Ok(directory) = fs::File::open(parent) {
        let _ = directory.sync_all();
    }
    Ok(())
}

fn write_item(
    output: &mut String,
    item: ItemDrop,
) {
    writeln!(output, "item_id = {}", item.item_id).unwrap();
    writeln!(output, "chance_per_million = {}", item.chance_per_million).unwrap();
    writeln!(output, "minimum_quantity = {}", item.minimum_quantity).unwrap();
    writeln!(output, "maximum_quantity = {}", item.maximum_quantity).unwrap();
    if let Some(quest_id) = item.quest_id {
        writeln!(output, "quest_id = {quest_id}").unwrap();
    }
    if let Some(skill_id) = item.required_skill_id {
        writeln!(output, "required_skill_id = {skill_id}").unwrap();
    }
}

fn write_mesos(
    output: &mut String,
    mesos: MesoDrop,
) {
    write_meso_values(
        output,
        mesos.chance_per_million,
        mesos.minimum_mesos,
        mesos.maximum_mesos,
    );
}

fn write_meso_values(
    output: &mut String,
    chance_per_million: u32,
    minimum_mesos: u32,
    maximum_mesos: u32,
) {
    writeln!(output, "chance_per_million = {}", chance_per_million).unwrap();
    writeln!(output, "minimum_mesos = {minimum_mesos}").unwrap();
    writeln!(output, "maximum_mesos = {maximum_mesos}").unwrap();
}

fn one_line(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character == '\n' || character == '\r' || character.is_control() {
                ' '
            } else {
                character
            }
        })
        .collect::<String>()
        .trim()
        .to_owned()
}

fn region_name(region: Region) -> &'static str {
    match region {
        Region::Gms => "gms",
        Region::Ems => "ems",
        Region::Bms => "bms",
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::loot::model::MobLoot;

    #[test]
    fn rendering_uses_destination_shape_and_stable_drop_order() {
        let catalog = LootCatalog {
            policy_name: "test".to_owned(),
            global_drops: Vec::new(),
            mobs: vec![MobLoot {
                mob_id: 100,
                name: Some("Test\nMob".to_owned()),
                drops: vec![
                    MobDrop::Item(ItemDrop {
                        item_id: 4_000_000,
                        chance_per_million: 10_000,
                        minimum_quantity: 1,
                        maximum_quantity: 2,
                        quest_id: None,
                        required_skill_id: None,
                    }),
                    MobDrop::Mesos(MesoDrop {
                        chance_per_million: 700_000,
                        minimum_mesos: 5,
                        maximum_mesos: 10,
                    }),
                ],
            }],
        };

        let rendered = render(
            &catalog,
            Region::Gms,
            &BTreeMap::from([("Mob.wz".to_owned(), 83)]),
        );

        assert!(rendered.contains("# Test Mob\n[[mobs]]\nmob_id = 100"));
        assert!(rendered.contains("# Reactor tables are not generated"));
        assert!(rendered.contains("item_id = 4000000"));
        assert!(rendered.contains("minimum_mesos = 5\nmaximum_mesos = 10"));
        assert!(!rendered.ends_with("\n\n"));
        toml::from_str::<toml::Value>(&rendered).expect("valid destination TOML");
    }

    #[test]
    fn atomic_write_refuses_an_existing_destination() {
        let directory = tempfile::tempdir().unwrap();
        let output = directory.path().join("loot.toml");
        fs::write(&output, "existing").unwrap();

        assert!(write_atomic(&output, "replacement", false).is_err());
        assert_eq!(fs::read_to_string(output).unwrap(), "existing");
    }
}
